title: Colaborando con Datos
author: A.M.Mayoral
email: asun.mayoral@umh.es
description: > # this means to ignore newlines until "baseurl:"
  Cómo utilizar GitHub para colaborar con datos en R.

# social links
twitter_username: asunmayoral # DO NOT include the @ character, or else the build will fail!
github_username:  asunmayoral # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
